// <auto-generated />
using System;
using FakeWebShop.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeWebShop.Persistence.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260216155118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.ClothingProduct", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Maat")
                        .HasColumnType("int");

                    b.Property<int>("Stof")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("ClothingProduct_Kleur");
                        });

                    b.HasDiscriminator().HasValue("ClothingProduct");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.DrinkProduct", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<int>("Inhoud")
                        .HasColumnType("int");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("DrinkProduct_Kleur");
                        });

                    b.HasDiscriminator().HasValue("DrinkProduct");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.NoteBook", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<string>("Formaat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("NoteBook_Kleur");
                        });

                    b.HasDiscriminator().HasValue("NoteBook");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Pen", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Pen");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Powerbank", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<int>("CapaciteitmAh")
                        .HasColumnType("int");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<bool>("OndersteuntFastCharging")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OutputType")
                        .HasColumnType("int");

                    b.Property<int>("PortTotaal")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Powerbank");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Sticker", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<double>("Breedte")
                        .HasColumnType("double");

                    b.Property<double>("Hoogte")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Sticker");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.ToteBag", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.Product");

                    b.Property<double>("Breedte")
                        .HasColumnType("double");

                    b.Property<double>("Hoogte")
                        .HasColumnType("double");

                    b.Property<string>("Kleur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Breedte")
                                .HasColumnName("ToteBag_Breedte");

                            t.Property("Hoogte")
                                .HasColumnName("ToteBag_Hoogte");

                            t.Property("Kleur")
                                .HasColumnName("ToteBag_Kleur");
                        });

                    b.HasDiscriminator().HasValue("ToteBag");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Hoodie", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.ClothingProduct");

                    b.Property<bool>("HasZipper")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PocketType")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("ClothingProduct_Kleur");
                        });

                    b.HasDiscriminator().HasValue("Hoodie");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Tshirt", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.ClothingProduct");

                    b.Property<int>("PrintType")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("ClothingProduct_Kleur");
                        });

                    b.HasDiscriminator().HasValue("Tshirt");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Drinkfles", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.DrinkProduct");

                    b.Property<bool>("IsThermisch")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Materiaal")
                        .HasColumnType("int");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("DrinkProduct_Kleur");
                        });

                    b.HasDiscriminator().HasValue("Drinkfles");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Mok", b =>
                {
                    b.HasBaseType("FakeWebShop.Persistence.Entities.Model.DrinkProduct");

                    b.Property<bool>("VaatwasserBestendig")
                        .HasColumnType("tinyint(1)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Kleur")
                                .HasColumnName("DrinkProduct_Kleur");
                        });

                    b.HasDiscriminator().HasValue("Mok");
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Product", b =>
                {
                    b.HasOne("FakeWebShop.Persistence.Entities.Model.Category", null)
                        .WithMany("Producten")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FakeWebShop.Persistence.Entities.Model.Category", b =>
                {
                    b.Navigation("Producten");
                });
#pragma warning restore 612, 618
        }
    }
}
